version: '3.8'

services:
  app:
    build: .
    command: sh -c "npm install && npm run dev"
    volumes:
      # 这是实现热重载的关键！
      # 1. 将本地当前目录挂载到容器的 /usr/src/app
      - .:/usr/src/app
      # 2. 但是，我们不希望本地的 node_modules 覆盖容器内的
      #    所以我们声明一个匿名卷来“保护”容器内的 node_modules
      - /usr/src/app/node_modules
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT_HOST}:${NGINX_PORT_CONTAINER}"
    environment:
      # 关键：设置一个自定义请求头，让 Nginx 知道这是开发模式
      # 我们通过这个头来触发 map 指令
      - NGINX_DISABLE_CACHE_HEADER=true
    volumes:
      - ${NGINX_CONF_HOST}:${NGINX_CONF_CONTAINER}:ro
      - ./uploads:/usr/share/nginx/html/uploads
    depends_on:
      - app

volumes:
  uploads_data: