services:
  app:
    # 告诉 Compose 使用当前目录的 Dockerfile 来构建一个基础镜像
    build: .
    # 覆盖 Dockerfile 中的默认 CMD，运行开发脚本
    # "tsx watch" 会监视文件变更并自动重启服务
    command: sh -c "npm install && npm run dev"
    ports:
      # 映射端口，方便在本地浏览器访问
      - "${PORT:-3000}:3000"
    volumes:
      # 这是实现热重载的关键！
      # 1. 将本地当前目录挂载到容器的 /usr/src/app
      - .:/usr/src/app
      # 2. 但是，我们不希望本地的 node_modules 覆盖容器内的
      #    所以我们声明一个匿名卷来“保护”容器内的 node_modules
      - /usr/src/app/node_modules
    env_file:
      - .env